export const CATALOG_REPOSITORY = 'CATALOG_REPOSITORY';
export const PURCHASE_REPOSITORY = 'PURCHASE_REPOSITORY';
export const PURCHASE_ITEM_REPOSITORY = 'PURCHASE_ITEM_REPOSITORY';
export const ITEM_REPOSITORY = 'ITEM_REPOSITORY';
export const STOCK_REPOSITORY = 'STOCK_REPOSITORY';
export const THIRDY_PARTHY_REPOSITORY = 'THIRDY_PARTY_REPOSITORY';
export const THIRDY_ORG_REPOSITORY = 'THIRDY_ORG_REPOSITORY';
export const PAYMENT_REPOSITORY = 'PAYMENT_REPOSITORY';
export const INCOME_REPOSITORY = 'INCOME_REPOSITORY';
export const INCOME_ITEMS_REPOSITORY = 'INCOME_ITEMS_REPOSITORY';
export const INVOICE_RESOLUTION_REPOSITORY = 'INVOICE_RESOLUTION_REPOSITORY';
export const CONSECUTIVE_REPOSITORY = 'CONSECUTIVE_REPOSITORY';
export const ACCOUNT_REPOSITORY = 'ACCOUNT_REPOSITORY';
export const ITEM_ACCOUNT_REPOSITORY = 'ITEM_ACCOUNT_REPOSITORY';
export const ACCOUNTING_SOURCE_REPOSITORY = 'ACCOUNTING_SOURCE_REPOSITORY';
export const ACCOUNTING_VOUCHER_REPOSITORY = 'ACCOUNTING_VOUCHER_REPOSITORY';
export const ACCOUNTING_VOUCHER_RECORD_REPOSITORY =
  'ACCOUNTING_VOUCHER_RECORD_REPOSITORY';
